var stars = 
['<img height=12 src="images/star-0.png"><img height=12 src="images/star-0.png"><img height=12 src="images/star-0.png"><img height=12 src="images/star-0.png"><img height=12 src="images/star-0.png">',
 '<img height=12 src="images/star-2.png"><img height=12 src="images/star-0.png"><img height=12 src="images/star-0.png"><img height=12 src="images/star-0.png"><img height=12 src="images/star-0.png">',
 '<img height=12 src="images/star-4.png"><img height=12 src="images/star-0.png"><img height=12 src="images/star-0.png"><img height=12 src="images/star-0.png"><img height=12 src="images/star-0.png">',
 '<img height=12 src="images/star-4.png"><img height=12 src="images/star-0.png"><img height=12 src="images/star-0.png"><img height=12 src="images/star-0.png"><img height=12 src="images/star-0.png">',
 '<img height=12 src="images/star-4.png"><img height=12 src="images/star-2.png"><img height=12 src="images/star-0.png"><img height=12 src="images/star-0.png"><img height=12 src="images/star-0.png">',
 '<img height=12 src="images/star-4.png"><img height=12 src="images/star-4.png"><img height=12 src="images/star-0.png"><img height=12 src="images/star-0.png"><img height=12 src="images/star-0.png">',
 '<img height=12 src="images/star-4.png"><img height=12 src="images/star-4.png"><img height=12 src="images/star-0.png"><img height=12 src="images/star-0.png"><img height=12 src="images/star-0.png">',
 '<img height=12 src="images/star-4.png"><img height=12 src="images/star-4.png"><img height=12 src="images/star-2.png"><img height=12 src="images/star-0.png"><img height=12 src="images/star-0.png">',
 '<img height=12 src="images/star-4.png"><img height=12 src="images/star-4.png"><img height=12 src="images/star-4.png"><img height=12 src="images/star-0.png"><img height=12 src="images/star-0.png">',
 '<img height=12 src="images/star-4.png"><img height=12 src="images/star-4.png"><img height=12 src="images/star-4.png"><img height=12 src="images/star-0.png"><img height=12 src="images/star-0.png">',
 '<img height=12 src="images/star-4.png"><img height=12 src="images/star-4.png"><img height=12 src="images/star-4.png"><img height=12 src="images/star-2.png"><img height=12 src="images/star-0.png">',
 '<img height=12 src="images/star-4.png"><img height=12 src="images/star-4.png"><img height=12 src="images/star-4.png"><img height=12 src="images/star-4.png"><img height=12 src="images/star-0.png">',
 '<img height=12 src="images/star-4.png"><img height=12 src="images/star-4.png"><img height=12 src="images/star-4.png"><img height=12 src="images/star-4.png"><img height=12 src="images/star-0.png">',
 '<img height=12 src="images/star-4.png"><img height=12 src="images/star-4.png"><img height=12 src="images/star-4.png"><img height=12 src="images/star-4.png"><img height=12 src="images/star-2.png">',
 '<img height=12 src="images/star-4.png"><img height=12 src="images/star-4.png"><img height=12 src="images/star-4.png"><img height=12 src="images/star-4.png"><img height=12 src="images/star-4.png">' ];
